@@include('files/regular.js', {})
@@include('files/dynamic_adapt.js', {})
@@include('files/common.js', {})
@@include('files/sliders.js', {})
@@include('files/header.js', {})
@@include('files/quotes.js', {}) 