@@include('files/common.js', {})
@@include('files/header.js', {})
@@include('files/quotes.js', {}) 
@@include('files/sections-box.js', {})
@@include('files/forums-slider.js', {})
@@include('files/moderation-pop-up.js', {})
@@include('files/custom-select-dynamic-load.js', {})
@@include('files/jBoxNotice.js', {})
@@include('files/nf-filter.js', {})
@@include('files/news.js', {})
@@include('files/bootstrap-datepicker-setup.js', {})
@@include('files/slide-sidebar.js', {})
@@include('files/quick-comment.js', {})
@@include('files/post-head.js', {})

// скрипты для страницы котировок
@@include('files/selector-links.js', {})
@@include('files/navbar.js', {})
@@include('files/trades-table.js', {})
@@include('files/qn-filters.js', {})
@@include('files/trade-tables-tooltip.js', {})
