@@include('files/common.js', {})
@@include('files/header.js', {})
@@include('files/quotes.js', {}) 
@@include('files/sections-box.js', {})
@@include('files/forums-slider.js', {})
@@include('files/moderation-pop-up.js', {})
@@include('files/custom-select.js', {})