@@include('libs/jquery-3.5.1.min.js', {})
@@include('libs/jquery.autocomplete.js', {})
@@include('libs/jquery.jBox.all.js', {})
@@include('libs/simplebar.js', {})
@@include('libs/swiper-bundle.min.js', {})
@@include('libs/bootstrap-datepicker.js', {})
@@include('libs/jquery.autocomplete.js', {})
